### ISSUE TITLE
Fixed in iOS 11

### ISSUE THREAD

**Issue by plivesey** [pawin/strange-wkwebview#2]
FYI, this seems to be fixed in iOS 11. I tested:

simulator 10.2 (issues reproduces easily)
device running iOS 11 (cannot reproduce)
simulator running iOS 11 (cannot reproduce)

(thanks for the project btw - it's been super useful for debugging these issues)

Suggestion: update the readme?

**Comment by pawin** [comment]
I've updated the readme, thanks!
